### PR TITLE
chore(deps): upgrade celo dependencies to 3.2.0

### PR DESCRIPTION
**Pull request by kathaypacific**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Updates all applicable @celo dependencies to 3.2.0.

- **Other information**:
- This is needed for Valora to also upgrade to the latest Celo sdk

### CODE REVIEW

**Review by nicolasbrugneaux — APPROVED** [review]

**Comment by jeanregisser** [comment]
Could we stop using fixed dependencies and use peerDepedencies instead to let the final app decide which version of the Celo SDK to use?
Upgrades for final apps would be simpler and we wouldn't need PRs like this one most of the time.
cc @kathaypacific @nicolasbrugneaux

**Comment by kathaypacific** [comment]
> Could we stop using fixed dependencies and use peerDepedencies instead to let the final app decide which version of the Celo SDK to use? Upgrades for final apps would be simpler and we wouldn't need PRs like this one most of the time. cc @kathaypacific @nicolasbrugneaux

hey @jeanregisser great suggestion, @dckesler suggested the same and implemented here https://github.com/celo-org/payments/pull/36 :D

**Comment by jeanregisser** [comment]
Amazing! thanks 🚀

**Comment by nicolasbrugneaux** [comment]
We published 0.0.14 which has peer dependencies :) from #36

**Pull request merged**
